---
- hosts: all
  sudo: true
  tasks:
    - name: update apt-cache
      apt: update_cache=yes
    - include: tasks/apache.yaml
    - include: tasks/mysql.yaml
    - include: tasks/php.yaml
    - include: tasks/git.yaml
